apiVersion: apps/v1
kind: Deployment
metadata:
  name: organic-ghee-app
  namespace: bhavana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: organic-ghee
  template:
    metadata:
      labels:
        app: organic-ghee
    spec:
      containers:
        - name: app
          image: bhavana686/organic-ghees:v1
          ports:
            - containerPort: 5656
          env:
            - name: PORT
              value: "5656"
            - name: MONGO_URI
              value: mongodb://mongo:27017/organic-ghee
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SESSION_SECRET
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EMAIL_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: organic-ghee-service
  namespace: bhavana
spec:
  type: NodePort
  selector:
    app: organic-ghee
  ports:
    - port: 5656 # 👈 updated
      targetPort: 5656 # 👈 updated
      nodePort: 32000 # 👈 external port
