apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.app.name } }
  namespace: { { .Values.namespace } }
spec:
  replicas: { { .Values.app.replicas } }
  selector:
    matchLabels:
      app: { { .Values.app.name } }
  template:
    metadata:
      labels:
        app: { { .Values.app.name } }
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          ports:
            - containerPort: { { .Values.app.port } }
          env:
            - name: PORT
              value: "{{ .Values.app.port }}"
            - name: MONGO_URI
              value: "mongodb://{{ .Values.mongo.name }}:{{ .Values.mongo.port }}/organic-ghee"
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: { { .Values.secret.name } }
                  key: SESSION_SECRET
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: { { .Values.secret.name } }
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: { { .Values.secret.name } }
                  key: EMAIL_PASS
